// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: seeddata.proto

package fuzzer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commands []int32 `protobuf:"varint,1,rep,packed,name=commands,proto3" json:"commands,omitempty"` // Use 'repeated' for lists of values
	NumBytes int32   `protobuf:"varint,2,opt,name=num_bytes,json=numBytes,proto3" json:"num_bytes,omitempty"`
}

func (x *SeedData) Reset() {
	*x = SeedData{}
	mi := &file_seeddata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedData) ProtoMessage() {}

func (x *SeedData) ProtoReflect() protoreflect.Message {
	mi := &file_seeddata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedData.ProtoReflect.Descriptor instead.
func (*SeedData) Descriptor() ([]byte, []int) {
	return file_seeddata_proto_rawDescGZIP(), []int{0}
}

func (x *SeedData) GetCommands() []int32 {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *SeedData) GetNumBytes() int32 {
	if x != nil {
		return x.NumBytes
	}
	return 0
}

var File_seeddata_proto protoreflect.FileDescriptor

var file_seeddata_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x65, 0x64, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x66, 0x75, 0x7a, 0x7a, 0x65, 0x72, 0x22, 0x43, 0x0a, 0x08, 0x53, 0x65, 0x65, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x25, 0x5a,
	0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x2d, 0x67, 0x6f, 0x2d, 0x74, 0x70,
	0x6d, 0x2d, 0x66, 0x75, 0x7a, 0x7a, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x66, 0x75,
	0x7a, 0x7a, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seeddata_proto_rawDescOnce sync.Once
	file_seeddata_proto_rawDescData = file_seeddata_proto_rawDesc
)

func file_seeddata_proto_rawDescGZIP() []byte {
	file_seeddata_proto_rawDescOnce.Do(func() {
		file_seeddata_proto_rawDescData = protoimpl.X.CompressGZIP(file_seeddata_proto_rawDescData)
	})
	return file_seeddata_proto_rawDescData
}

var file_seeddata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_seeddata_proto_goTypes = []any{
	(*SeedData)(nil), // 0: fuzzer.SeedData
}
var file_seeddata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seeddata_proto_init() }
func file_seeddata_proto_init() {
	if File_seeddata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seeddata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seeddata_proto_goTypes,
		DependencyIndexes: file_seeddata_proto_depIdxs,
		MessageInfos:      file_seeddata_proto_msgTypes,
	}.Build()
	File_seeddata_proto = out.File
	file_seeddata_proto_rawDesc = nil
	file_seeddata_proto_goTypes = nil
	file_seeddata_proto_depIdxs = nil
}
