name: Fuzz Test with Docker

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  fuzzing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure corpus directory exists
        run: |
          if [ ! -d "fuzz/corpus" ]; then
            mkdir -p fuzz/corpus
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.fuzz -t my-fuzz-image .

      - name: Run fuzz tests in Docker container
        run: |
          docker run --rm -e GOCACHE=/fuzz/corpus my-fuzz-image go test ./fuzz/fuzzer -fuzz=FuzzTPMSequences -fuzztime=30s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-corpus
          path: fuzz/corpus
